<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.4" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.3.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sample.Contracts\Sample.Contracts.csproj" />
  </ItemGroup>

</Project>
